In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [4]:
pokemon_data01= pd.read_csv("pokemon_data.csv")
pokemon_data01

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [5]:
newdf=pokemon_data01.loc[(pokemon_data01["Type 1"]=="Rock") & (pokemon_data01["Type 2"]=="Grass")]
newdf.to_csv("newone.csv")
# newdf=newdf.reset_index()  #we reset index to new in sequence
newdf.reset_index(inplace=True)     #instead of assigning it we can use inplace="True"
newdf

,index,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,377,345,Lileep,Rock,Grass,66,41,77,61,87,23,3,False
1,378,346,Cradily,Rock,Grass,86,81,97,81,107,43,3,False

In [6]:
pokemon_data01.loc[~pokemon_data01["Name"].str.contains("Mega")]  # we removed mega naming values from table with usnig 
                                                #str.contains("name")  and using tild symbol(~) saying not instead of "!"

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [7]:
import re
pokemon_data01.loc[pokemon_data01["Type 1"].str.contains("Dragon|Ground",regex=True)]
pokemon_data01.loc[pokemon_data01["Type 1"].str.contains("dragon|ground",flags=re.I,regex=True)]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
32,27,Sandshrew,Ground,NaN,50,75,85,20,30,40,1,False
33,28,Sandslash,Ground,NaN,75,100,110,45,55,65,1,False
55,50,Diglett,Ground,NaN,10,55,25,35,45,95,1,False
56,51,Dugtrio,Ground,NaN,35,80,50,50,70,120,1,False
112,104,Cubone,Ground,NaN,50,50,95,40,50,35,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
712,646,KyuremWhite Kyurem,Dragon,Ice,125,120,90,170,100,95,5,True
774,704,Goomy,Dragon,NaN,45,50,35,55,75,40,6,False
775,705,Sliggoo,Dragon,NaN,68,75,53,83,113,60,6,False
776,706,Goodra,Dragon,NaN,90,100,70,110,150,80,6,False
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True

In [8]:
 pokemon_data01.loc[pokemon_data01["Name"].str.contains("^du[a-z]*",flags=re.I,regex=True)]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
56,51,Dugtrio,Ground,NaN,35,80,50,50,70,120,1,False
221,206,Dunsparce,Normal,NaN,100,70,70,65,65,45,2,False
292,269,Dustox,Bug,Poison,60,50,70,50,90,65,3,False
388,355,Duskull,Ghost,NaN,20,40,90,30,90,25,3,False
389,356,Dusclops,Ghost,NaN,40,70,130,60,130,25,3,False
529,477,Dusknoir,Ghost,NaN,45,100,135,65,135,45,4,False
639,578,Duosion,Psychic,NaN,65,40,50,125,60,30,5,False
641,580,Ducklett,Water,Flying,62,44,50,44,50,55,5,False
693,632,Durant,Bug,Steel,58,109,112,48,48,109,5,False

In [24]:
pokemon_data01.loc[pokemon_data01["Type 1"]=="Ground","Type 1"]="Earth"   #changed all values named as Ground
pokemon_data01.loc[(pokemon_data01["Type 1"]=="Earth")]
pokemon_data01.loc[pokemon_data01["Type 1"]=="Earth","Type 1"]="Ground"
pokemon_data01.loc[(pokemon_data01["Type 1"]=="Ground")]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
32,27,Sandshrew,Ground,NaN,50,75,85,20,30,40,1,False
33,28,Sandslash,Ground,NaN,75,100,110,45,55,65,1,False
55,50,Diglett,Ground,NaN,10,55,25,35,45,95,1,False
56,51,Dugtrio,Ground,NaN,35,80,50,50,70,120,1,False
112,104,Cubone,Ground,NaN,50,50,95,40,50,35,1,False
113,105,Marowak,Ground,NaN,60,80,110,50,80,45,1,False
119,111,Rhyhorn,Ground,Rock,80,85,95,30,30,25,1,False
120,112,Rhydon,Ground,Rock,105,130,120,45,45,40,1,False
222,207,Gligar,Ground,Flying,65,75,105,35,65,85,2,False
250,231,Phanpy,Ground,NaN,90,60,60,40,40,40,2,False
251,232,Donphan,Ground,NaN,90,120,120,60,60,50,2,False
359,328,Trapinch,Ground,NaN,45,100,45,45,45,10,3,False
360,329,Vibrava,Ground,Dragon,50,70,50,50,50,70,3,False
361,330,Flygon,Ground,Dragon,80,100,80,80,80,100,3,False
375,343,Baltoy,Ground,Psychic,40,40,55,40,70,55,3,False
376,344,Claydol,Ground,Psychic,60,70,105,70,120,75,3,False
423,383,Groudon,Ground,NaN,100,150,140,100,90,90,3,True
424,383,GroudonPrimal Groudon,Ground,Fire,100,180,160,150,90,90,3,True
499,449,Hippopotas,Ground,NaN,68,72,78,38,42,32,4,False
500,450,Hippowdon,Ground,NaN,108,112,118,68,72,47,4,False
515,464,Rhyperior,Ground,Rock,115,140,130,55,55,40,4,False
523,472,Gliscor,Ground,Flying,75,95,125,45,75,95,4,False
588,529,Drilbur,Ground,NaN,60,85,40,30,45,68,5,False
589,530,Excadrill,Ground,Steel,110,135,60,50,65,88,5,False
611,551,Sandile,Ground,Dark,50,72,35,35,35,65,5,False
612,552,Krokorok,Ground,Dark,60,82,45,45,45,74,5,False
613,553,Krookodile,Ground,Dark,95,117,80,65,70,92,5,False
679,618,Stunfisk,Ground,Electric,109,66,84,81,99,32,5,False
683,622,Golett,Ground,Ghost,59,74,50,35,50,35,5,False
684,623,Golurk,Ground,Ghost,89,124,80,55,80,55,5,False
708,645,LandorusIncarnate Forme,Ground,Flying,89,125,90,115,80,101,5,True
709,645,LandorusTherian Forme,Ground,Flying,89,145,90,105,80,91,5,True

In [26]:
pokemon_data01.loc[pokemon_data01["Type 1"]=="Ground","Legendry"]=True
pokemon_data01.loc[(pokemon_data01["Type 1"]=="Ground")]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Legendry
32,27,Sandshrew,Ground,NaN,50,75,85,20,30,40,1,False,True
33,28,Sandslash,Ground,NaN,75,100,110,45,55,65,1,False,True
55,50,Diglett,Ground,NaN,10,55,25,35,45,95,1,False,True
56,51,Dugtrio,Ground,NaN,35,80,50,50,70,120,1,False,True
112,104,Cubone,Ground,NaN,50,50,95,40,50,35,1,False,True
113,105,Marowak,Ground,NaN,60,80,110,50,80,45,1,False,True
119,111,Rhyhorn,Ground,Rock,80,85,95,30,30,25,1,False,True
120,112,Rhydon,Ground,Rock,105,130,120,45,45,40,1,False,True
222,207,Gligar,Ground,Flying,65,75,105,35,65,85,2,False,True
250,231,Phanpy,Ground,NaN,90,60,60,40,40,40,2,False,True
251,232,Donphan,Ground,NaN,90,120,120,60,60,50,2,False,True
359,328,Trapinch,Ground,NaN,45,100,45,45,45,10,3,False,True
360,329,Vibrava,Ground,Dragon,50,70,50,50,50,70,3,False,True
361,330,Flygon,Ground,Dragon,80,100,80,80,80,100,3,False,True
375,343,Baltoy,Ground,Psychic,40,40,55,40,70,55,3,False,True
376,344,Claydol,Ground,Psychic,60,70,105,70,120,75,3,False,True
423,383,Groudon,Ground,NaN,100,150,140,100,90,90,3,True,True
424,383,GroudonPrimal Groudon,Ground,Fire,100,180,160,150,90,90,3,True,True
499,449,Hippopotas,Ground,NaN,68,72,78,38,42,32,4,False,True
500,450,Hippowdon,Ground,NaN,108,112,118,68,72,47,4,False,True
515,464,Rhyperior,Ground,Rock,115,140,130,55,55,40,4,False,True
523,472,Gliscor,Ground,Flying,75,95,125,45,75,95,4,False,True
588,529,Drilbur,Ground,NaN,60,85,40,30,45,68,5,False,True
589,530,Excadrill,Ground,Steel,110,135,60,50,65,88,5,False,True
611,551,Sandile,Ground,Dark,50,72,35,35,35,65,5,False,True
612,552,Krokorok,Ground,Dark,60,82,45,45,45,74,5,False,True
613,553,Krookodile,Ground,Dark,95,117,80,65,70,92,5,False,True
679,618,Stunfisk,Ground,Electric,109,66,84,81,99,32,5,False,True
683,622,Golett,Ground,Ghost,59,74,50,35,50,35,5,False,True
684,623,Golurk,Ground,Ghost,89,124,80,55,80,55,5,False,True
708,645,LandorusIncarnate Forme,Ground,Flying,89,125,90,115,80,101,5,True,True
709,645,LandorusTherian Forme,Ground,Flying,89,145,90,105,80,91,5,True,True

In [27]:
pokemon_data01=pd.read_csv("modified01.csv")

In [38]:
pokemon_data01.loc[pokemon_data01["Attack"]>100,["Legendary","Legendary.1"]]=["Great","Best"]
pokemon_data01.loc[(pokemon_data01["Legendary.1"]=="Best")]

,Unnamed: 0,Legendary,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Legendary.1
7,7,Great,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,Best
8,8,Great,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,Best
12,12,Great,9,BlastoiseMega Blastoise,Water,NaN,79,103,120,135,115,78,Best
19,19,Great,15,BeedrillMega Beedrill,Bug,Poison,65,150,40,15,80,145,Best
39,39,Great,34,Nidoking,Poison,Ground,81,102,77,85,75,85,Best
...,...,...,...,...,...,...,...,...,...,...,...,...,...
793,793,Great,717,Yveltal,Dark,Flying,126,131,95,131,98,99,Best
796,796,Great,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,Best
797,797,Great,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,Best
798,798,Great,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,Best
799,799,Great,721,Volcanion,Fire,Water,80,110,120,130,90,70,Best

In [39]:
pokemon_data01.groupby(["Type 1"]).mean()

,Unnamed: 0,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed
Type 1,,,,,,,,
Bug,368.072464,334.492754,56.884058,70.971014,70.724638,53.869565,64.797101,61.681159
Dark,507.387097,461.354839,66.806452,88.387097,70.225806,74.645161,69.516129,76.161290
Dragon,521.843750,474.375000,83.312500,112.125000,86.375000,96.843750,88.843750,83.031250
Electric,400.590909,363.500000,59.795455,69.090909,66.295455,90.022727,73.704545,84.500000
Fairy,494.529412,449.529412,74.117647,61.529412,65.705882,78.529412,84.705882,48.588235
Fighting,400.444444,363.851852,69.851852,96.777778,65.925926,53.111111,64.703704,66.074074
Fire,360.942308,327.403846,69.903846,84.769231,67.769231,88.980769,72.211538,74.442308
Flying,746.500000,677.750000,70.750000,78.750000,66.250000,94.250000,72.500000,102.500000
Ghost,536.281250,486.500000,64.437500,73.781250,81.187500,79.343750,76.468750,64.343750
Grass,380.414286,344.871429,67.271429,73.214286,70.800000,77.500000,70.428571,61.928571
Ground,392.312500,356.281250,73.781250,95.750000,84.843750,56.468750,62.750000,63.906250
Ice,465.666667,423.541667,72.000000,72.750000,71.416667,77.541667,76.291667,63.458333
Normal,351.581633,319.173469,77.275510,73.469388,59.846939,55.816327,63.724490,71.551020
Poison,278.285714,251.785714,67.250000,74.678571,68.821429,60.428571,64.392857,63.571429
Psychic,420.105263,380.807018,70.631579,71.456140,67.684211,98.403509,86.280702,81.491228
Rock,431.840909,392.727273,65.363636,92.863636,100.795455,63.340909,75.477273,55.909091
Steel,486.296296,442.851852,65.222222,92.703704,126.370370,67.518519,80.629630,55.259259
Water,333.312500,303.089286,72.062500,74.151786,72.946429,74.812500,70.517857,65.964286

In [42]:
pokemon_data01.groupby(["Type 1"]).mean().sort_values("Attack",ascending=False)

,Unnamed: 0,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed
Type 1,,,,,,,,
Dragon,521.843750,474.375000,83.312500,112.125000,86.375000,96.843750,88.843750,83.031250
Fighting,400.444444,363.851852,69.851852,96.777778,65.925926,53.111111,64.703704,66.074074
Ground,392.312500,356.281250,73.781250,95.750000,84.843750,56.468750,62.750000,63.906250
Rock,431.840909,392.727273,65.363636,92.863636,100.795455,63.340909,75.477273,55.909091
Steel,486.296296,442.851852,65.222222,92.703704,126.370370,67.518519,80.629630,55.259259
Dark,507.387097,461.354839,66.806452,88.387097,70.225806,74.645161,69.516129,76.161290
Fire,360.942308,327.403846,69.903846,84.769231,67.769231,88.980769,72.211538,74.442308
Flying,746.500000,677.750000,70.750000,78.750000,66.250000,94.250000,72.500000,102.500000
Poison,278.285714,251.785714,67.250000,74.678571,68.821429,60.428571,64.392857,63.571429
Water,333.312500,303.089286,72.062500,74.151786,72.946429,74.812500,70.517857,65.964286
Ghost,536.281250,486.500000,64.437500,73.781250,81.187500,79.343750,76.468750,64.343750
Normal,351.581633,319.173469,77.275510,73.469388,59.846939,55.816327,63.724490,71.551020
Grass,380.414286,344.871429,67.271429,73.214286,70.800000,77.500000,70.428571,61.928571
Ice,465.666667,423.541667,72.000000,72.750000,71.416667,77.541667,76.291667,63.458333
Psychic,420.105263,380.807018,70.631579,71.456140,67.684211,98.403509,86.280702,81.491228
Bug,368.072464,334.492754,56.884058,70.971014,70.724638,53.869565,64.797101,61.681159
Electric,400.590909,363.500000,59.795455,69.090909,66.295455,90.022727,73.704545,84.500000
Fairy,494.529412,449.529412,74.117647,61.529412,65.705882,78.529412,84.705882,48.588235